# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2443c1da278b6de4bec9180d48afb2deaa5a31592e88141c8941413bc1ba24a3be92207cfbc03ee8219c3d7751b8e0c28f49ee90d9793f27aae18f719c2e4024

test:
  secret_key_base: 3e3b7f865363c95afc6d610296626e021996da89d83884c10ca74ea7a7841247ee49afe40149763ffb6b9d10c2b881b84a810f99d3c0e8de9642bb1b14773435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
